### PR TITLE
Release `0.2.0`

### PR DESCRIPTION
**Pull request by robbot006**
This is a draft of changelog for the `0.2.0` release.
Here you can find all related translations changes: [0.1.1...master](https://github.com/flarum-lang/persian/compare/0.1.1...master).

> ### ⚠️ Do not merge this pull request manually ⚠️
> 
> You should **[approve](https://github.com/rob006-software/flarum-translations/wiki/How-to-approve-release-pull-request)** this pull request instead. After approving, I will automatically update it (release date needs to be adjusted), merge, and tag a new release. You can read more about the process on [forum](https://discuss.flarum.org/d/20807-simplify-translation-process-with-weblate/76).

<details>
<summary>Show release notes preview</summary>

## 0.2.0

**General changes**:

* Updated Day.js translations.
* Updated Flarum core translations.

**Added support for new extensions**:

* [`clarkwinkelmann/flarum-ext-author-change`](https://github.com/clarkwinkelmann/flarum-ext-author-change)
* [`datlechin/flarum-birthdays`](https://github.com/datlechin/flarum-birthdays)
* [`fof/ban-ips`](https://github.com/FriendsOfFlarum/ban-ips)
* [`fof/byobu`](https://github.com/FriendsOfFlarum/byobu)
* [`fof/drafts`](https://github.com/FriendsOfFlarum/drafts)
* [`fof/filter`](https://github.com/FriendsOfFlarum/filter)
* [`fof/ignore-users`](https://github.com/FriendsOfFlarum/ignore-users)
* [`fof/merge-discussions`](https://github.com/FriendsOfFlarum/merge-discussions)
* [`fof/polls`](https://github.com/FriendsOfFlarum/polls)
* [`fof/prevent-necrobumping`](https://github.com/FriendsOfFlarum/prevent-necrobumping)
* [`fof/secure-https`](https://github.com/FriendsOfFlarum/secure-https)
* [`fof/share-social`](https://github.com/FriendsOfFlarum/share-social)
* [`fof/spamblock`](https://github.com/FriendsOfFlarum/spamblock)
* [`fof/split`](https://github.com/FriendsOfFlarum/split)
* [`fof/terms`](https://github.com/FriendsOfFlarum/terms)
* [`the-turk/flarum-diff`](https://github.com/the-turk/flarum-diff)

**Updated translations for extensions**:

* [`flarum/sticky`](https://github.com/flarum/sticky)
* [`flarum/tags`](https://github.com/flarum/tags)

All changes: [0.1.1...0.2.0](https://github.com/flarum-lang/persian/compare/0.1.1...0.2.0).

</details>

### CODE REVIEW

**Comment by rob006** [comment]
@amirrezakhakpour Just as a note, this is an automated PR generated by bot. The idea is to simplify release process for language pack maintainers - all you need is to approve this pull request and bot will handle the rest. You can read more about the process at forum: https://discuss.flarum.org/d/20807-simplify-translation-process-with-weblate/76 . If you don't want to use this feature, let me know.

**Comment by rob006** [comment]
@amirrezakhakpour It's been over 2 months with no response from you. It is important to tag new releases when new transliterations appear, because by default composer installs only stable versions of packages. It means that all translations added after last release are inaccessible for most of the users. In case of no response from you, I'm going to mark this language pack as unmaintained, so its state will be more clear for users. It means that:
* I'll add info in readme that this language pack is searching for maintainer.
* Command for installing package will use `dev-master` as version, so users will benefit from translations not included in last stable release.
* All translations on Weblate will be marked as unverified, so community will be able to edit them without any restrictions.
* You will keep permissions on Weblate and this repository, but if anyone will volunteer to maintain this language pack, he will replace you as maintainer.

**Comment by rob006** [comment]
> In case of no response from you, I'm going to mark this language pack as unmaintained, so its state will be more clear for users. It means that:
> * I'll add info in readme that this language pack is searching for maintainer.
> * Command for installing package will use `dev-master` as version, so users will benefit from translations not included in last stable release.
> * All translations on Weblate will be marked as unverified, so community will be able to edit them without any restrictions.
> * You will keep permissions on Weblate and this repository, but if anyone will volunteer to maintain this language pack, he will replace you as maintainer.

Done.

**Review by behdanisohrab — APPROVED** [review]
This Changes looks good to me.

**Comment by robbot006** [comment]
Success! Now you can announce new release on [forum](https://discuss.flarum.org/t/languages):

~~~markdown
## Version [`0.2.0`](https://github.com/flarum-lang/persian/releases/tag/0.2.0)

**General changes**:

* Updated Day.js translations.
* Updated Flarum core translations.


**Added support for new extensions**:

* [`clarkwinkelmann/flarum-ext-author-change`](https://github.com/clarkwinkelmann/flarum-ext-author-change)
* [`datlechin/flarum-birthdays`](https://github.com/datlechin/flarum-birthdays)
* [`fof/ban-ips`](https://github.com/FriendsOfFlarum/ban-ips)
* [`fof/byobu`](https://github.com/FriendsOfFlarum/byobu)
* [`fof/drafts`](https://github.com/FriendsOfFlarum/drafts)
* [`fof/filter`](https://github.com/FriendsOfFlarum/filter)
* [`fof/ignore-users`](https://github.com/FriendsOfFlarum/ignore-users)
* [`fof/merge-discussions`](https://github.com/FriendsOfFlarum/merge-discussions)
* [`fof/polls`](https://github.com/FriendsOfFlarum/polls)
* [`fof/prevent-necrobumping`](https://github.com/FriendsOfFlarum/prevent-necrobumping)
* [`fof/secure-https`](https://github.com/FriendsOfFlarum/secure-https)
* [`fof/share-social`](https://github.com/FriendsOfFlarum/share-social)
* [`fof/spamblock`](https://github.com/FriendsOfFlarum/spamblock)
* [`fof/split`](https://github.com/FriendsOfFlarum/split)
* [`fof/terms`](https://github.com/FriendsOfFlarum/terms)
* [`the-turk/flarum-diff`](https://github.com/the-turk/flarum-diff)


**Updated translations for extensions**:

* [`flarum/sticky`](https://github.com/flarum/sticky)
* [`flarum/tags`](https://github.com/flarum/tags)


All changes: [0.1.1...0.2.0](https://github.com/flarum-lang/persian/compare/0.1.1...0.2.0).

In order to update run these commands:

```console
composer update flarum-lang/persian
php flarum cache:clear
```

~~~

**Comment by behdanisohrab** [comment]
done https://discuss.flarum.org/d/35866-flarum-persian-language-pack-zban-farsy-bray-flarom
now its waiting for approval.

**Pull request merged**
